import Head from "next/head";
import React from "react";

function MyApp({ Component, pageProps }) {
  return (
    <React.Fragment>
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.9.0/devicon.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.9.0/devicon.min.css"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-Regular.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-Medium.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-MediumItalic.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-SemiBold.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-SemiBoldItalic.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-Light.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-LightItalic.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-Italic.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-ExtraBold.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-ExtraBoldItalic.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-Bold.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-BoldItalic.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-Black.ttf"
          as="font"
          crossOrigin="anomynous"
        />
        <link
          rel="preload"
          href="/font/TTF/OpenSauceSans-BlackItalic.ttf"
          as="font"
          crossOrigin="anomynous"
        />
      </Head>
      <Component {...pageProps} />
    </React.Fragment>
  );
}

export default MyApp;
